# Generated by Django 4.1.3 on 2022-12-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Desc', models.TextField()),
                ('Image', models.ImageField(upload_to='static\\Management_photos')),
                ('Email', models.EmailField(max_length=254)),
                ('Facebook', models.CharField(max_length=100, unique=True)),
                ('Twitter', models.CharField(max_length=100, unique=True)),
                ('Whatsapp', models.CharField(max_length=100, unique=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Management',
            },
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Desc', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Visitors',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='static/images')),
                ('Desc', models.TextField()),
                ('Publish', models.BooleanField(default=True)),
                ('Tags', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
        ),
    ]
